# Generated by Django 4.1.1 on 2023-04-02 03:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "character",
                    models.CharField(
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                        verbose_name="汉字",
                    ),
                ),
                ("total_time", models.IntegerField(verbose_name="总次数")),
                ("accurate_time", models.IntegerField(verbose_name="正确次数")),
                (
                    "accuracy",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="正确率"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterOfGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(max_length=1, verbose_name="汉字")),
                ("grade", models.IntegerField(verbose_name="年级")),
                ("total_time", models.IntegerField(verbose_name="总次数")),
                ("accurate_time", models.IntegerField(verbose_name="正确次数")),
                (
                    "accuracy",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="正确率"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "content",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="题目内容",
                    ),
                ),
                ("answer", models.BooleanField(default=True, verbose_name="正误")),
                ("total", models.IntegerField(default=0, verbose_name="出现总次数")),
                ("right", models.IntegerField(default=0, verbose_name="正确次数")),
                (
                    "accuracy",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseOfGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=32, verbose_name="题目内容")),
                ("grade", models.IntegerField(verbose_name="年级")),
                ("total", models.IntegerField(default=0, verbose_name="出现总次数")),
                ("right", models.IntegerField(default=0, verbose_name="正确次数")),
                (
                    "accuracy",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseV1Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_account", models.CharField(max_length=32, verbose_name="账号")),
                (
                    "name",
                    models.CharField(default="测试用户", max_length=8, verbose_name="姓名"),
                ),
                (
                    "grade",
                    models.SmallIntegerField(
                        choices=[
                            (1, "一年级"),
                            (2, "二年级"),
                            (3, "三年级"),
                            (4, "四年级"),
                            (5, "五年级"),
                            (6, "六年级"),
                        ],
                        default=1,
                        null=True,
                        verbose_name="年级",
                    ),
                ),
                ("total_characters", models.IntegerField(verbose_name="总字数")),
                ("score", models.IntegerField(verbose_name="分数")),
                (
                    "literacy",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="识字量"
                    ),
                ),
                (
                    "accuracy_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
                    ),
                ),
                (
                    "exercise_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="时间"
                    ),
                ),
                (
                    "wrong",
                    models.CharField(default="无", max_length=128, verbose_name="错误汉字"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseV2Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="测试用户", max_length=8, verbose_name="姓名"),
                ),
                (
                    "grade",
                    models.SmallIntegerField(
                        choices=[
                            (1, "一年级"),
                            (2, "二年级"),
                            (3, "三年级"),
                            (4, "四年级"),
                            (5, "五年级"),
                            (6, "六年级"),
                        ],
                        default=1,
                        null=True,
                        verbose_name="年级",
                    ),
                ),
                (
                    "stu_account",
                    models.CharField(
                        default="njnustu", max_length=32, verbose_name="账号"
                    ),
                ),
                (
                    "total_characters",
                    models.IntegerField(default=0, verbose_name="总字数"),
                ),
                (
                    "wrong_characters",
                    models.IntegerField(default=0, verbose_name="错误数"),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="分数"
                    ),
                ),
                ("test_time", models.IntegerField(default=0, verbose_name="测试用时")),
                (
                    "accuracy_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
                    ),
                ),
                (
                    "avg_speed",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="平均阅读速度",
                    ),
                ),
                (
                    "exercise_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="时间"
                    ),
                ),
                (
                    "wrong",
                    models.CharField(default="无", max_length=128, verbose_name="错误汉字"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseV3Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="测试用户", max_length=8, verbose_name="姓名"),
                ),
                (
                    "grade",
                    models.SmallIntegerField(
                        choices=[
                            (1, "一年级"),
                            (2, "二年级"),
                            (3, "三年级"),
                            (4, "四年级"),
                            (5, "五年级"),
                            (6, "六年级"),
                        ],
                        default=1,
                        null=True,
                        verbose_name="年级",
                    ),
                ),
                (
                    "stu_account",
                    models.CharField(
                        default="njnustu", max_length=32, verbose_name="账号"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="分数"
                    ),
                ),
                (
                    "total_characters",
                    models.IntegerField(default=0, verbose_name="总字数"),
                ),
                (
                    "wrong_characters",
                    models.IntegerField(default=0, verbose_name="错误数"),
                ),
                (
                    "accuracy_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
                    ),
                ),
                (
                    "avg_speed",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="平均阅读速度",
                    ),
                ),
                (
                    "exercise_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="时间"
                    ),
                ),
                (
                    "wrong",
                    models.CharField(default="无", max_length=128, verbose_name="错误汉字"),
                ),
                ("judge_all", models.IntegerField(default=0, verbose_name="测试句子个数")),
                (
                    "judge_right",
                    models.IntegerField(default=0, verbose_name="判断正确句子个数"),
                ),
                (
                    "judge_accuracy",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="判断正确率"
                    ),
                ),
                ("test_time", models.IntegerField(default=0, verbose_name="测试用时")),
            ],
        ),
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "content",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="题目内容",
                    ),
                ),
                ("total", models.IntegerField(default=0, verbose_name="出现总次数")),
                ("right", models.IntegerField(default=0, verbose_name="正确次数")),
                (
                    "accuracy",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhraseOfGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=8, verbose_name="题目内容")),
                ("grade", models.IntegerField(verbose_name="年级")),
                ("total", models.IntegerField(default=0, verbose_name="出现总次数")),
                ("right", models.IntegerField(default=0, verbose_name="正确次数")),
                (
                    "accuracy",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StuTestInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stu_name",
                    models.CharField(default="stu", max_length=32, verbose_name="学生"),
                ),
                (
                    "stu_account",
                    models.CharField(
                        default="njnustu", max_length=32, verbose_name="账号"
                    ),
                ),
                (
                    "grade",
                    models.SmallIntegerField(
                        choices=[
                            (1, "一年级"),
                            (2, "二年级"),
                            (3, "三年级"),
                            (4, "四年级"),
                            (5, "五年级"),
                            (6, "六年级"),
                        ],
                        default=1,
                        null=True,
                        verbose_name="年级",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="时间"
                    ),
                ),
                (
                    "test_type",
                    models.SmallIntegerField(
                        choices=[(1, "准确性测试"), (2, "流畅性测试一"), (3, "流畅性测试二")],
                        default=1,
                        verbose_name="类型",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=4, verbose_name="分数"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TecInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tec_account",
                    models.CharField(default="tec", max_length=32, verbose_name="账号"),
                ),
                (
                    "tec_password",
                    models.CharField(
                        default="njnutec", max_length=32, verbose_name="密码"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WavRecognitionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu", models.CharField(max_length=4, verbose_name="测试学生")),
                ("path", models.CharField(max_length=64, verbose_name="音频路径")),
                ("target", models.CharField(max_length=32, verbose_name="识别目标")),
                ("result", models.CharField(max_length=32, verbose_name="识别结果")),
                (
                    "exercise_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="时间"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StuExactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
                (
                    "grade",
                    models.SmallIntegerField(
                        choices=[
                            (1, "一年级"),
                            (2, "二年级"),
                            (3, "三年级"),
                            (4, "四年级"),
                            (5, "五年级"),
                            (6, "六年级"),
                        ],
                        default=1,
                        null=True,
                        verbose_name="年级",
                    ),
                ),
                ("account", models.CharField(max_length=32, verbose_name="账号")),
                ("password", models.CharField(max_length=32, verbose_name="密码")),
                (
                    "admintec",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reading_system.tecinfo",
                        verbose_name="管理员",
                    ),
                ),
            ],
        ),
    ]
