# Generated by Django 4.1.1 on 2022-10-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="stutestinfo", name="test_time",),
        migrations.AddField(
            model_name="stutestinfo",
            name="score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=4, verbose_name="分数"
            ),
        ),
        migrations.AddField(
            model_name="stutestinfo",
            name="stu_account",
            field=models.CharField(default="njnuxxx", max_length=32, verbose_name="账号"),
        ),
        migrations.AddField(
            model_name="stutestinfo",
            name="stu_name",
            field=models.CharField(default="stuxxx", max_length=32, verbose_name="学生"),
        ),
        migrations.AddField(
            model_name="stutestinfo",
            name="test_type",
            field=models.SmallIntegerField(
                choices=[(1, "准确性测试"), (2, "流畅性测试一"), (3, "流畅性测试二")],
                default=1,
                verbose_name="类型",
            ),
        ),
        migrations.AddField(
            model_name="stutestinfo",
            name="time",
            field=models.DateTimeField(null=True, verbose_name="时间"),
        ),
    ]
