# Generated by Django 4.1.1 on 2023-07-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterofgrade",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
