# Generated by Django 4.1.1 on 2023-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0002_alter_wavrecognitionresult_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="stuexactinfo",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(1, "男"), (2, "女")], default=1, null=True, verbose_name="性别"
            ),
        ),
    ]
