# Generated by Django 4.1.1 on 2023-11-30 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0003_stuexactinfo_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseV4Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_account", models.CharField(max_length=32, verbose_name="账号")),
                (
                    "name",
                    models.CharField(default="测试用户", max_length=8, verbose_name="姓名"),
                ),
                (
                    "grade",
                    models.SmallIntegerField(default=5, null=True, verbose_name="年级"),
                ),
                ("total_num", models.IntegerField(default=0, verbose_name="总字数")),
                ("right_num", models.IntegerField(default=0, verbose_name="正确汉字个数")),
                ("wrong_num", models.IntegerField(default=0, verbose_name="错误汉字个数")),
                (
                    "wrong_characters",
                    models.CharField(max_length=256, verbose_name="错误汉字"),
                ),
                (
                    "accuracy_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
                    ),
                ),
                (
                    "exercise_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="时间"
                    ),
                ),
            ],
        ),
    ]
