# Generated by Django 4.1.1 on 2022-10-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0004_exercise"),
    ]

    operations = [
        migrations.RenameModel(old_name="Exercise", new_name="ExerciseV3",),
    ]
