# Generated by Django 4.1.1 on 2023-12-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0004_exercisev4result"),
    ]

    operations = [
        migrations.AddField(
            model_name="wavrecognitionresult",
            name="errmsg",
            field=models.CharField(default="无", max_length=256, verbose_name="错误信息"),
        ),
    ]
