# Generated by Django 4.1.1 on 2022-10-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0005_rename_exercise_exercisev3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercisev3", old_name="test_type", new_name="grade",
        ),
    ]
