# Generated by Django 4.1.1 on 2022-10-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0006_rename_test_type_exercisev3_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="stutestinfo",
            name="grade",
            field=models.SmallIntegerField(default=3, null=True, verbose_name="年级"),
        ),
    ]
