# Generated by Django 4.1.1 on 2022-10-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0008_stuexactinfo_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stuexactinfo",
            name="grade",
            field=models.SmallIntegerField(
                choices=[
                    (1, "一年级"),
                    (2, "二年级"),
                    (3, "三年级"),
                    (4, "四年级"),
                    (5, "五年级"),
                    (6, "六年级"),
                ],
                default=3,
                null=True,
                verbose_name="年级",
            ),
        ),
        migrations.AlterField(
            model_name="stutestinfo",
            name="grade",
            field=models.SmallIntegerField(
                choices=[
                    (1, "一年级"),
                    (2, "二年级"),
                    (3, "三年级"),
                    (4, "四年级"),
                    (5, "五年级"),
                    (6, "六年级"),
                ],
                default=3,
                null=True,
                verbose_name="年级",
            ),
        ),
    ]
