# Generated by Django 4.1.1 on 2022-10-26 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "reading_system",
            "0010_alter_stuexactinfo_grade_alter_stutestinfo_grade_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stutestinfo",
            name="time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, null=True, verbose_name="时间"
            ),
        ),
    ]
