# Generated by Django 4.1.1 on 2022-10-26 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0011_alter_stutestinfo_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stutestinfo",
            name="time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="时间"
            ),
        ),
    ]
