# Generated by Django 4.1.1 on 2022-11-22 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0012_alter_stutestinfo_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseV3Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stu_account",
                    models.CharField(
                        default="njnustu", max_length=32, verbose_name="账号"
                    ),
                ),
                (
                    "total_characters",
                    models.IntegerField(default=0, verbose_name="总字数"),
                ),
                (
                    "wrong_characters",
                    models.IntegerField(default=0, verbose_name="错误数"),
                ),
                (
                    "accuracy_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
                    ),
                ),
                (
                    "avg_speed",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="平均阅读速度"
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="时间"
                    ),
                ),
            ],
        ),
    ]
