# Generated by Django 4.1.1 on 2022-11-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0013_exercisev3result"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseV1Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stu_account",
                    models.CharField(
                        default="njnustu", max_length=32, verbose_name="账号"
                    ),
                ),
                (
                    "total_characters",
                    models.IntegerField(default=0, verbose_name="总字数"),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="分数"
                    ),
                ),
                (
                    "accuracy_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseV2Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stu_account",
                    models.CharField(
                        default="njnustu", max_length=32, verbose_name="账号"
                    ),
                ),
                (
                    "total_characters",
                    models.IntegerField(default=0, verbose_name="总字数"),
                ),
                (
                    "wrong_characters",
                    models.IntegerField(default=0, verbose_name="错误数"),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="分数"
                    ),
                ),
                (
                    "test_time",
                    models.CharField(default=60, max_length=100, verbose_name="测试用时"),
                ),
                (
                    "accuracy_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
                    ),
                ),
                (
                    "avg_speed",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="平均阅读速度"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="exercisev3result", name="time",),
        migrations.AddField(
            model_name="exercisev3result",
            name="score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, verbose_name="分数"
            ),
        ),
    ]
