# Generated by Django 4.1.1 on 2023-02-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0014_exercisev1result_exercisev2result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisev1result",
            name="score",
            field=models.IntegerField(verbose_name="分数"),
        ),
        migrations.AlterField(
            model_name="exercisev1result",
            name="stu_account",
            field=models.CharField(max_length=32, verbose_name="账号"),
        ),
        migrations.AlterField(
            model_name="exercisev1result",
            name="total_characters",
            field=models.IntegerField(verbose_name="总字数"),
        ),
    ]
