# Generated by Django 4.1.1 on 2023-02-01 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0015_alter_exercisev1result_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisev1result",
            name="exercise_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="时间"
            ),
        ),
        migrations.AddField(
            model_name="exercisev1result",
            name="literacy",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, verbose_name="识字量"
            ),
        ),
        migrations.AddField(
            model_name="exercisev2result",
            name="exercise_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="时间"
            ),
        ),
        migrations.AddField(
            model_name="exercisev3result",
            name="exercise_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="时间"
            ),
        ),
    ]
