# Generated by Django 4.1.1 on 2023-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0016_exercisev1result_exercise_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(max_length=1, verbose_name="汉字")),
                ("total_time", models.IntegerField(verbose_name="总次数")),
                ("accurate_time", models.IntegerField(verbose_name="正确次数")),
                (
                    "accuracy",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="正确率"
                    ),
                ),
            ],
        ),
    ]
