# Generated by Django 4.1.1 on 2023-02-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0017_character"),
    ]

    operations = [
        migrations.RemoveField(model_name="character", name="id",),
        migrations.AlterField(
            model_name="character",
            name="character",
            field=models.CharField(
                max_length=1, primary_key=True, serialize=False, verbose_name="汉字"
            ),
        ),
    ]
