# Generated by Django 4.1.1 on 2023-02-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0018_remove_character_id_alter_character_character"),
    ]

    operations = [
        migrations.CreateModel(
            name="WavRecognitionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu", models.CharField(max_length=4, verbose_name="测试学生")),
                ("path", models.CharField(max_length=64, verbose_name="音频路径")),
                ("target", models.CharField(max_length=32, verbose_name="识别目标")),
                ("result", models.CharField(max_length=32, verbose_name="识别结果")),
            ],
        ),
    ]
