# Generated by Django 4.1.1 on 2023-02-01 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0019_wavrecognitionresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="wavrecognitionresult",
            name="exercise_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="时间"
            ),
        ),
    ]
