# Generated by Django 4.1.1 on 2023-02-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0020_wavrecognitionresult_exercise_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisev1result",
            name="literacy",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="识字量"
            ),
        ),
    ]
