# Generated by Django 4.1.1 on 2023-02-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0021_alter_exercisev1result_literacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisev1result",
            name="wrong",
            field=models.CharField(default="无", max_length=128, verbose_name="错误汉字"),
        ),
        migrations.AddField(
            model_name="exercisev2result",
            name="wrong",
            field=models.CharField(default="无", max_length=128, verbose_name="错误汉字"),
        ),
        migrations.AddField(
            model_name="exercisev3result",
            name="wrong",
            field=models.CharField(default="无", max_length=128, verbose_name="错误汉字"),
        ),
    ]
