# Generated by Django 4.1.1 on 2023-02-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reading_system",
            "0022_exercisev1result_wrong_exercisev2result_wrong_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisev1result",
            name="literacy",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="识字量"
            ),
        ),
        migrations.AlterField(
            model_name="exercisev2result",
            name="avg_speed",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="平均阅读速度"
            ),
        ),
    ]
