# Generated by Django 4.1.1 on 2023-02-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0023_alter_exercisev1result_literacy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisev2result",
            name="score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="分数"
            ),
        ),
        migrations.AlterField(
            model_name="exercisev3result",
            name="avg_speed",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="平均阅读速度"
            ),
        ),
        migrations.AlterField(
            model_name="exercisev3result",
            name="score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="分数"
            ),
        ),
    ]
