# Generated by Django 4.1.1 on 2023-02-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0025_remove_exercisev3_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisev3",
            name="answer",
            field=models.BooleanField(default=True, verbose_name="正误"),
        ),
    ]
