# Generated by Django 4.1.1 on 2023-02-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0027_exercise_delete_exercisev3"),
    ]

    operations = [
        migrations.RemoveField(model_name="exercise", name="id",),
        migrations.AddField(
            model_name="exercise",
            name="right",
            field=models.IntegerField(default=0, verbose_name="正确次数"),
        ),
        migrations.AddField(
            model_name="exercise",
            name="total",
            field=models.IntegerField(default=0, verbose_name="出现总次数"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="content",
            field=models.CharField(
                max_length=32, primary_key=True, serialize=False, verbose_name="题目内容"
            ),
        ),
    ]
