# Generated by Django 4.1.1 on 2023-02-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reading_system",
            "0028_remove_exercise_id_exercise_right_exercise_total_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisev3result",
            name="judge_accuracy",
            field=models.IntegerField(default=0, verbose_name="判断正确率"),
        ),
        migrations.AddField(
            model_name="exercisev3result",
            name="judge_all",
            field=models.IntegerField(default=0, verbose_name="测试句子个数"),
        ),
        migrations.AddField(
            model_name="exercisev3result",
            name="judge_right",
            field=models.IntegerField(default=0, verbose_name="判断正确句子个数"),
        ),
    ]
