# Generated by Django 4.1.1 on 2023-02-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0030_exercisev3result_test_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="accuracy",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
            ),
        ),
    ]
