# Generated by Django 4.1.1 on 2023-02-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0031_exercise_accuracy"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisev1result",
            name="grade",
            field=models.SmallIntegerField(
                choices=[
                    (1, "一年级"),
                    (2, "二年级"),
                    (3, "三年级"),
                    (4, "四年级"),
                    (5, "五年级"),
                    (6, "六年级"),
                ],
                default=1,
                null=True,
                verbose_name="年级",
            ),
        ),
        migrations.AddField(
            model_name="exercisev1result",
            name="name",
            field=models.CharField(default="测试用户", max_length=8, verbose_name="姓名"),
        ),
        migrations.AddField(
            model_name="exercisev2result",
            name="grade",
            field=models.SmallIntegerField(
                choices=[
                    (1, "一年级"),
                    (2, "二年级"),
                    (3, "三年级"),
                    (4, "四年级"),
                    (5, "五年级"),
                    (6, "六年级"),
                ],
                default=1,
                null=True,
                verbose_name="年级",
            ),
        ),
        migrations.AddField(
            model_name="exercisev2result",
            name="name",
            field=models.CharField(default="测试用户", max_length=8, verbose_name="姓名"),
        ),
        migrations.AddField(
            model_name="exercisev3result",
            name="grade",
            field=models.SmallIntegerField(
                choices=[
                    (1, "一年级"),
                    (2, "二年级"),
                    (3, "三年级"),
                    (4, "四年级"),
                    (5, "五年级"),
                    (6, "六年级"),
                ],
                default=1,
                null=True,
                verbose_name="年级",
            ),
        ),
        migrations.AddField(
            model_name="exercisev3result",
            name="name",
            field=models.CharField(default="测试用户", max_length=8, verbose_name="姓名"),
        ),
    ]
