# Generated by Django 4.1.1 on 2023-02-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reading_system",
            "0032_exercisev1result_grade_exercisev1result_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisev3result",
            name="judge_accuracy",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, verbose_name="判断正确率"
            ),
        ),
    ]
