# Generated by Django 4.1.1 on 2023-03-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0033_alter_exercisev3result_judge_accuracy"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterOfGrade",
            fields=[
                (
                    "character",
                    models.CharField(
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                        verbose_name="汉字",
                    ),
                ),
                ("grade", models.IntegerField(verbose_name="年级")),
                ("total_time", models.IntegerField(verbose_name="总次数")),
                ("accurate_time", models.IntegerField(verbose_name="正确次数")),
                (
                    "accuracy",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="正确率"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseOfGrade",
            fields=[
                (
                    "content",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="题目内容",
                    ),
                ),
                ("grade", models.IntegerField(verbose_name="年级")),
                ("answer", models.BooleanField(default=True, verbose_name="正误")),
                ("total", models.IntegerField(default=0, verbose_name="出现总次数")),
                ("right", models.IntegerField(default=0, verbose_name="正确次数")),
                (
                    "accuracy",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="正确率"
                    ),
                ),
            ],
        ),
    ]
