# Generated by Django 4.1.1 on 2023-03-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reading_system", "0034_characterofgrade_exerciseofgrade"),
    ]

    operations = [
        migrations.RemoveField(model_name="exerciseofgrade", name="answer",),
    ]
